apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: spelloux/udagram-frontend:v1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-pg-secrets
        imagePullPolicy: Always