apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: spelloux/udagram-api-user:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-pg-secrets
        imagePullPolicy: Always
        volumeMounts:
        - name: env-aws
          mountPath: "/root/.aws/"
        imagePullPolicy: Always
      volumes:
        - name: env-aws
          configMap:
            name: env-aws      
