# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag reverseproxy spelloux/reverseproxy:v1
    - run: docker tag udagram-api-feed spelloux/udagram-api-feed:v1
    - run: docker tag udagram-api-user spelloux/udagram-api-user:v1
    - run: docker tag udagram-database:local spelloux/udagram-database:v1
    - run: docker tag udagram-frontend:local spelloux/udagram-frontend:v1
    
    - name: Authenticate to registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: docker push spelloux/reverseproxy:v1
    - run: docker push spelloux/udagram-api-feed:v1
    - run: docker push spelloux/udagram-api-user:v1
    - run: docker push spelloux/udagram-database:v1
    - run: docker push spelloux/udagram-frontend:v1



